[project]
name = "python-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-json-logger>=3.2.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = ["ruff>=0.9.3"]
